import type { CreditPurchase, Transaction } from "@/lib/api";

export const transactionToCreditPurchase = (transaction: Transaction): CreditPurchase => ({
	creditCardId: transaction.creditCardId,
	currency: transaction.currency,
	currentInstallment: transaction.currentInstallment ?? 1,
	debtSplit: transaction.debtSplit,
	description: transaction.description ?? "",
	exchangeRate: transaction.exchangeRate,
	feeAmount: transaction.feeAmount,
	feeDescription: transaction.feeDescription,
	fees: transaction.fees,
	hasRefund: transaction.hasRefund,
	id: transaction.id,
	installmentAmount: transaction.installmentAmount ?? transaction.amount,
	installments: transaction.installments ?? 1,
	isRefund: transaction.isRefund,
	originalAmount: transaction.originalAmount,
	parentId: transaction.parentId,
	purchaseDate: transaction.date,
	refund: transaction.refund,
	refundOfPurchaseId: transaction.refundOfPurchaseId,
	statementId: transaction.statementId ?? "",
	storeName: transaction.storeName,
	tagIds: transaction.tagIds,
	tags: transaction.tags,
	time: transaction.time,
	totalAmount: transaction.amount,
});
